/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as UnauthenticatedIndexImport } from './routes/_unauthenticated/index'
import { Route as UnauthenticatedLogoutImport } from './routes/_unauthenticated/logout'
import { Route as UnauthenticatedLoginImport } from './routes/_unauthenticated/login'
import { Route as AuthenticatedQueuesIndexImport } from './routes/_authenticated/queues/index'
import { Route as AuthenticatedQueuesIdIndexImport } from './routes/_authenticated/queues/$id/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedIndexRoute = UnauthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedLogoutRoute = UnauthenticatedLogoutImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const UnauthenticatedLoginRoute = UnauthenticatedLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedQueuesIndexRoute = AuthenticatedQueuesIndexImport.update({
  path: '/queues/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedQueuesIdIndexRoute = AuthenticatedQueuesIdIndexImport.update(
  {
    path: '/queues/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/login': {
      id: '/_unauthenticated/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthenticatedLoginImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/logout': {
      id: '/_unauthenticated/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof UnauthenticatedLogoutImport
      parentRoute: typeof rootRoute
    }
    '/_unauthenticated/': {
      id: '/_unauthenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/queues/': {
      id: '/_authenticated/queues/'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/queues/$id/': {
      id: '/_authenticated/queues/$id/'
      path: '/queues/$id'
      fullPath: '/queues/$id'
      preLoaderRoute: typeof AuthenticatedQueuesIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedQueuesIndexRoute,
    AuthenticatedQueuesIdIndexRoute,
  }),
  UnauthenticatedLoginRoute,
  UnauthenticatedLogoutRoute,
  UnauthenticatedIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_unauthenticated/login",
        "/_unauthenticated/logout",
        "/_unauthenticated/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/queues/",
        "/_authenticated/queues/$id/"
      ]
    },
    "/_unauthenticated/login": {
      "filePath": "_unauthenticated/login.tsx"
    },
    "/_unauthenticated/logout": {
      "filePath": "_unauthenticated/logout.tsx"
    },
    "/_unauthenticated/": {
      "filePath": "_unauthenticated/index.tsx"
    },
    "/_authenticated/queues/": {
      "filePath": "_authenticated/queues/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/queues/$id/": {
      "filePath": "_authenticated/queues/$id/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
