name: ESLint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: cache
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/eslint.yml') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: eslint
              run: |-
                  npm install
                  npx eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0
