name: Prettier

on:
    push:
    pull_request:

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - uses: actions/cache@v2
              name: cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: prettier
              run: |-
                  npx prettier src --ignore-unknown --list-different
