name: TypeScript

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    typescript:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - uses: actions/cache@v2
              name: cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/tsc.yml') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-
            - name: typescript
              run: |-
                  npm install
                  npx tsc --noEmit
